---
- hosts: all
  vars:
    applications:
      - 1password
      - adium
      - alfred
      - charles
      - dropbox
      - duet
      - firefox
      - google-chrome
      - handbrake
      - microsoft-office
      - phpstorm
      - sequel-pro
      - sketch
      - sourcetree
      - sublime-text3
      - virtualbox
    brews:
      - rbenv
      - ruby-build
      - node
      - wget
      - git
      - bash
      - ruby
      - jq
      - mysql
      - openssl
  tasks:
    - include: tasks/checkAndSetupBasics.yml
    - include: tasks/installApplications.yml
    - include: tasks/installBrews.yml
    - include: tasks/settings/changeMacOSXSettings.yml