---
- hosts: all
  vars:
    applications:
      - 1password
      - adium
      - alfred
      - charles
      - dropbox
      - duet
      - firefox
      - google-chrome
      - handbrake
      - microsoft-office
      - phpstorm
      - sequel-pro
      - sketch
      - sourcetree
      - sublime-text3
      - virtualbox
    brews:
      - rbenv
      - ruby-build
      - node
      - wget
      - git
      - bash
      - ruby
      - jq
      - mysql
      - openssl
    users: 
      - name:   mbachmann
        first:  Mathias
        last:   Bachmann
        mail:   design@designerdrug.net
      - name:   gshumway
        first:  Gordon
        last:   Shumway
        mail:   design@designerdrug.net
  tasks:
    #- include: tasks/checkAndSetupBasics.yml            tags=basics
    #- include: tasks/installApplications.yml            tags=apps
    #- include: tasks/installBrews.yml                   tags=tools
    #- include: tasks/settings/changeMacOSXSettings.yml  tags=os
    - include: tasks/settings/createUser.yml            tags=user