---

- name: Up&Run | Create Users
  become: true
  become_method: sudo
  command: dscl . create /Users/{{ item.name }}
  with_items: '{{ users }}'
  when: users is defined

- name: Up&Run | Set real names of Users
  become: true
  become_method: sudo
  command: 'dscl . create /Users/{{ item.name }} RealName "{ item.first }} {{ item.last }}"'
  with_items: '{{ users }}'
  when: users is defined

- name: Up&Run | Set Bash for every User
  become: true
  become_method: sudo
  command: 'dscl . create /Users/{{ item.name }} UserShell /bin/bash'
  with_items: '{{ users }}'
  when: users is defined

#- name: Up&Run | Set ID for every new User
#  become: true
#  become_method: sudo
#  command: "dscl . create /Users/{{ item.name }} UniqueID {{ item.id }}"
#  with_items: '{{ users }}'
#  when: users is defined