export PS1=' \[\e[1;36m\]\W\[\e[1;33m\]$(parse_git_branch) \[\e[0m\]'

export BLOCKSIZE=1k

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

alias ltr="ls -lisatr"

# Git
alias gittags='git tag -l | gsort -V'
alias gitclean='git branch -r --merged origin/master | grep -v "origin/[HEAD|master]"'

# Finder
alias showhidden="defaults write com.apple.finder AppleShowAllFiles TRUE && killall Finder"
alias hidehidden="defaults write com.apple.finder AppleShowAllFiles FALSE && killall Finder"
